services:
  keycloak:
    build:
      context: .
      args:
        KC_HEALTH_ENABLED: "true"
        KC_METRICS_ENABLED: "true"
        KC_DB: "postgres"
        KC_HTTP_ENABLED: "true"
        PROXY_ADDRESS_FORWARDING: "true"
        KC_HOSTNAME: "localhost"
        KC_LOG_LEVEL: "INFO"
    environment:
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://postgres/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "password"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME: "localhost"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: